/* eslint-disable */
// This file is generated by scripts/generate-config-registry.mjs.
// Edit the config snapshots, then regenerate this file instead of hand-editing it.

import draftCurrentWorkingMap from "../../../configs/hudson-hustle/drafts/current-working/map.json";
import draftCurrentWorkingMeta from "../../../configs/hudson-hustle/drafts/current-working/meta.json";
import draftCurrentWorkingRules from "../../../configs/hudson-hustle/drafts/current-working/rules.json";
import draftCurrentWorkingTickets from "../../../configs/hudson-hustle/drafts/current-working/tickets.json";
import draftCurrentWorkingVisuals from "../../../configs/hudson-hustle/drafts/current-working/visuals.json";
import releaseV03AtlanticHobokenMap from "../../../configs/hudson-hustle/releases/v0.3-atlantic-hoboken/map.json";
import releaseV03AtlanticHobokenMeta from "../../../configs/hudson-hustle/releases/v0.3-atlantic-hoboken/meta.json";
import releaseV03AtlanticHobokenRules from "../../../configs/hudson-hustle/releases/v0.3-atlantic-hoboken/rules.json";
import releaseV03AtlanticHobokenTickets from "../../../configs/hudson-hustle/releases/v0.3-atlantic-hoboken/tickets.json";
import releaseV03AtlanticHobokenVisuals from "../../../configs/hudson-hustle/releases/v0.3-atlantic-hoboken/visuals.json";
import type { RegisteredConfigBundle, SnapshotMap, SnapshotMeta, SnapshotRules, SnapshotTickets, SnapshotVisuals } from "./config-types";

export const generatedHudsonHustleConfigRegistry: Record<string, RegisteredConfigBundle> = {
  "current-working": {
    configId: "current-working",
    configPath: "configs/hudson-hustle/drafts/current-working",
    mode: "draft",
    meta: draftCurrentWorkingMeta as SnapshotMeta,
    map: draftCurrentWorkingMap as SnapshotMap,
    tickets: draftCurrentWorkingTickets as SnapshotTickets,
    rules: draftCurrentWorkingRules as SnapshotRules,
    visuals: draftCurrentWorkingVisuals as SnapshotVisuals
  },
  "v0.3-atlantic-hoboken": {
    configId: "v0.3-atlantic-hoboken",
    configPath: "configs/hudson-hustle/releases/v0.3-atlantic-hoboken",
    mode: "release",
    meta: releaseV03AtlanticHobokenMeta as SnapshotMeta,
    map: releaseV03AtlanticHobokenMap as SnapshotMap,
    tickets: releaseV03AtlanticHobokenTickets as SnapshotTickets,
    rules: releaseV03AtlanticHobokenRules as SnapshotRules,
    visuals: releaseV03AtlanticHobokenVisuals as SnapshotVisuals
  }
};
