/* eslint-disable */
// This file is generated by scripts/config/generate-config-registry.mjs.
// Edit the config snapshots, then regenerate this file instead of hand-editing it.

import draftCurrentWorkingMap from "../../../configs/hudson-hustle/drafts/current-working/map.json";
import draftCurrentWorkingMeta from "../../../configs/hudson-hustle/drafts/current-working/meta.json";
import draftCurrentWorkingRules from "../../../configs/hudson-hustle/drafts/current-working/rules.json";
import draftCurrentWorkingTickets from "../../../configs/hudson-hustle/drafts/current-working/tickets.json";
import draftCurrentWorkingVisuals from "../../../configs/hudson-hustle/drafts/current-working/visuals.json";
import draftV04NextWaveMap from "../../../configs/hudson-hustle/drafts/v0.4-next-wave/map.json";
import draftV04NextWaveMeta from "../../../configs/hudson-hustle/drafts/v0.4-next-wave/meta.json";
import draftV04NextWaveRules from "../../../configs/hudson-hustle/drafts/v0.4-next-wave/rules.json";
import draftV04NextWaveTickets from "../../../configs/hudson-hustle/drafts/v0.4-next-wave/tickets.json";
import draftV04NextWaveVisuals from "../../../configs/hudson-hustle/drafts/v0.4-next-wave/visuals.json";
import releaseV03AtlanticHobokenMap from "../../../configs/hudson-hustle/releases/v0.3-atlantic-hoboken/map.json";
import releaseV03AtlanticHobokenMeta from "../../../configs/hudson-hustle/releases/v0.3-atlantic-hoboken/meta.json";
import releaseV03AtlanticHobokenRules from "../../../configs/hudson-hustle/releases/v0.3-atlantic-hoboken/rules.json";
import releaseV03AtlanticHobokenTickets from "../../../configs/hudson-hustle/releases/v0.3-atlantic-hoboken/tickets.json";
import releaseV03AtlanticHobokenVisuals from "../../../configs/hudson-hustle/releases/v0.3-atlantic-hoboken/visuals.json";
import releaseV04FlushingNewarkAirportMap from "../../../configs/hudson-hustle/releases/v0.4-flushing-newark-airport/map.json";
import releaseV04FlushingNewarkAirportMeta from "../../../configs/hudson-hustle/releases/v0.4-flushing-newark-airport/meta.json";
import releaseV04FlushingNewarkAirportRules from "../../../configs/hudson-hustle/releases/v0.4-flushing-newark-airport/rules.json";
import releaseV04FlushingNewarkAirportTickets from "../../../configs/hudson-hustle/releases/v0.4-flushing-newark-airport/tickets.json";
import releaseV04FlushingNewarkAirportVisuals from "../../../configs/hudson-hustle/releases/v0.4-flushing-newark-airport/visuals.json";
import type { RegisteredConfigBundle, SnapshotMap, SnapshotMeta, SnapshotRules, SnapshotTickets, SnapshotVisuals } from "./config-types";

export const generatedHudsonHustleConfigRegistry: Record<string, RegisteredConfigBundle> = {
  "current-working": {
    configId: "current-working",
    configPath: "configs/hudson-hustle/drafts/current-working",
    mode: "draft",
    meta: draftCurrentWorkingMeta as SnapshotMeta,
    map: draftCurrentWorkingMap as SnapshotMap,
    tickets: draftCurrentWorkingTickets as SnapshotTickets,
    rules: draftCurrentWorkingRules as SnapshotRules,
    visuals: draftCurrentWorkingVisuals as SnapshotVisuals
  },
  "v0.4-next-wave": {
    configId: "v0.4-next-wave",
    configPath: "configs/hudson-hustle/drafts/v0.4-next-wave",
    mode: "draft",
    meta: draftV04NextWaveMeta as SnapshotMeta,
    map: draftV04NextWaveMap as SnapshotMap,
    tickets: draftV04NextWaveTickets as SnapshotTickets,
    rules: draftV04NextWaveRules as SnapshotRules,
    visuals: draftV04NextWaveVisuals as SnapshotVisuals
  },
  "v0.3-atlantic-hoboken": {
    configId: "v0.3-atlantic-hoboken",
    configPath: "configs/hudson-hustle/releases/v0.3-atlantic-hoboken",
    mode: "release",
    meta: releaseV03AtlanticHobokenMeta as SnapshotMeta,
    map: releaseV03AtlanticHobokenMap as SnapshotMap,
    tickets: releaseV03AtlanticHobokenTickets as SnapshotTickets,
    rules: releaseV03AtlanticHobokenRules as SnapshotRules,
    visuals: releaseV03AtlanticHobokenVisuals as SnapshotVisuals
  },
  "v0.4-flushing-newark-airport": {
    configId: "v0.4-flushing-newark-airport",
    configPath: "configs/hudson-hustle/releases/v0.4-flushing-newark-airport",
    mode: "release",
    meta: releaseV04FlushingNewarkAirportMeta as SnapshotMeta,
    map: releaseV04FlushingNewarkAirportMap as SnapshotMap,
    tickets: releaseV04FlushingNewarkAirportTickets as SnapshotTickets,
    rules: releaseV04FlushingNewarkAirportRules as SnapshotRules,
    visuals: releaseV04FlushingNewarkAirportVisuals as SnapshotVisuals
  }
};
